/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASK1_H_RPCGEN
#define _ASK1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intpair {
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
	int n;
	int a;
};
typedef struct intpair intpair;

struct intminmax {
	int min;
	int max;
	struct {
		u_int MM_len;
		int *MM_val;
	} MM;
};
typedef struct intminmax intminmax;

struct intmul {
	struct {
		u_int aY_len;
		int *aY_val;
	} aY;
};
typedef struct intmul intmul;

struct intavg {
	int avg;
};
typedef struct intavg intavg;

#define ASK1_PROG 0x23451111
#define ASK1_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINMAX 1
extern  intminmax * minmax_1(intpair *, CLIENT *);
extern  intminmax * minmax_1_svc(intpair *, struct svc_req *);
#define MUL 2
extern  intmul * mul_1(intpair *, CLIENT *);
extern  intmul * mul_1_svc(intpair *, struct svc_req *);
#define AVG 3
extern  intavg * avg_1(intpair *, CLIENT *);
extern  intavg * avg_1_svc(intpair *, struct svc_req *);
extern int ask1_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINMAX 1
extern  intminmax * minmax_1();
extern  intminmax * minmax_1_svc();
#define MUL 2
extern  intmul * mul_1();
extern  intmul * mul_1_svc();
#define AVG 3
extern  intavg * avg_1();
extern  intavg * avg_1_svc();
extern int ask1_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intpair (XDR *, intpair*);
extern  bool_t xdr_intminmax (XDR *, intminmax*);
extern  bool_t xdr_intmul (XDR *, intmul*);
extern  bool_t xdr_intavg (XDR *, intavg*);

#else /* K&R C */
extern bool_t xdr_intpair ();
extern bool_t xdr_intminmax ();
extern bool_t xdr_intmul ();
extern bool_t xdr_intavg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASK1_H_RPCGEN */
