/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ask1.h"

bool_t
xdr_intpair (XDR *xdrs, intpair *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len, 10,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_intminmax (XDR *xdrs, intminmax *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->MM.MM_val, (u_int *) &objp->MM.MM_len, 5,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_intmul (XDR *xdrs, intmul *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->aY.aY_val, (u_int *) &objp->aY.aY_len, 10,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_intavg (XDR *xdrs, intavg *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->avg))
		 return FALSE;
	return TRUE;
}
